# Generated by Django 5.0.3 on 2024-03-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.TextField()),
            ],
        ),
    ]
